name: iOS One-Time Setup

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Build iOS
        shell: bash
        run: |
          bundle exec fastlane ios init_ci --verbose
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GH_PAT: ${{ secrets.GH_PAT }}

          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          #          MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          FASTLANE_VERBOSE: 1

          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}